service: looplend-backend
useDotenv: true

frameworkVersion: '3'

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  timeout: 10
  versionFunctions: false
  environment:
    DB_URL: ${env:DB_URL}
package:
  excludeDevDependencies: false
  individually: true

custom:
  esbuild:
    bundle: true
    target: node18
    minify: false
    external:
      - pg-query-stream
      - nock
      - mock-aws-s3
      - oracledb
      - mysql2
      - mysql
      - tedious
      - better-sqlite3
      - sqlite3

resources:
  Outputs:
    authorizerArn:
      Value: !GetAtt AuthorizerLambdaFunction.Arn
      Export:
        Name: authorizerArn
functions:
  - ${file(infra/user-functions.yml)}
  - ${file(infra/products-functions.yml)}
#  - ${file(infra/conv-functions.yml)}
  - ${file(infra/wishlist-functions.yml)}
#  - ${file(infra/rentals-functions.yml)}
