service: looplend-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  timeout: 10
  versionFunctions: false

package:
  patterns:
    - '!*/**'
    - methods/libs/**

functions:
  - ${file(./infra/user-functions.yml)}
  - ${file(./infra/products-functions.yml)}
  - ${file(./infra/conv-functions.yml)}
  - ${file(./infra/wishlist-functions.yml)}
  - ${file(./infra/rentals-functions.yml)}
