service: looplend-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  timeout: 10
  versionFunctions: false

package:
  excludeDevDependencies: false
  individually: true
  patterns:
    - '!**'                # Exclude all files by default
    - methods/libs/**         # Include function directories

functions:
  - ${file(infra/user-functions.yml)}
#  - ${file(infra/products-functions.yml)}
#  - ${file(infra/conv-functions.yml)}
#  - ${file(infra/wishlist-functions.yml)}
#  - ${file(infra/rentals-functions.yml)}
