#getConversations:
#  handler: methods/conv.getConversations
#  events:
#    - http:
#        path: /conversations
#        method: get
#        cors: true
#        authorizer:
#          name: authorizer
#          resultTtlInSeconds: 0
#          identitySource: method.request.header.Authorization
#          type: request
#
#getConversationMessages:
#  handler: methods/conv.getConversationMessages
#  events:
#    - http:
#        path: /conversations/{cID}/messages
#        method: get
#        cors: true
#        authorizer:
#          name: authorizer
#          resultTtlInSeconds: 0
#          identitySource: method.request.header.Authorization
#          type: request
#
#sendConversationMessage:
#  handler: methods/conv.sendConversationMessage
#  events:
#    - http:
#        path: /conversations/{cID}/messages
#        method: post
#        cors: true
#        authorizer:
#          name: authorizer
#          resultTtlInSeconds: 0
#          identitySource: method.request.header.Authorization
#          type: request
