getConversationMessages:
  handler: methods/conv.listMessages
  events:
    - http:
        path: /conversations/{rID}/messages
        method: get
        cors: true
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0
          type: request

sendConversationMessage:
  handler: methods/conv.sendMessage
  events:
    - http:
        path: /conversations/{rID}/messages
        method: post
        cors: true
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0
          type: request
