createProduct:
  handler: methods/users.getUserInfo
  events:
    - http:
        path: /products
        cors: true
        method: post
        authorizer: authorizer

#editProduct:
#  handler: handler.editProduct
#  events:
#    - http:
#        path: /products/{pID}
#        method: put
#        authorizer: authorizer
#
#deleteProduct:
#  handler: handler.deleteProduct
#  events:
#    - http:
#        path: /products/{pID}
#        method: delete
#        authorizer: authorizer
#
#sendProductFeedback:
#  handler: handler.sendProductFeedback
#  events:
#    - http:
#        path: /products/{pID}/feedbacks
#        method: post
#        authorizer: authorizer
#
#getProducts:
#  handler: handler.getProducts
#  events:
#    - http:
#        path: /products
#        method: get
#        authorizer: authorizer
