createProduct:
  handler: methods/products.createProduct
  events:
    - http:
        path: /products
        cors: true
        method: post
        authorizer: authorizer

editProduct:
  handler: methods/products.editProduct
  events:
    - http:
        path: /products/{pID}
        method: put
        cors: true
        authorizer: authorizer

deleteProduct:
  handler: methods/products.deleteProduct
  events:
    - http:
        path: /products/{pID}
        method: delete
        cors: true
        authorizer: authorizer
#
#sendProductFeedback:
#  handler: handler.sendProductFeedback
#  events:
#    - http:
#        path: /products/{pID}/feedbacks
#        method: post
#        authorizer: authorizer
#
listProducts:
  handler: methods/products.listProducts
  events:
    - http:
        path: /products
        method: get
        cors: true
        authorizer: authorizer
