getRental:
  handler: methods/rentals.getRental
  events:
    - http:
        path: /rentals/{rID}
        method: get
        cors: true
        authorizer: authorizer

listRentals:
  handler: methods/rentals.listRentals
  events:
    - http:
        path: /rentals
        method: get
        cors: true
        authorizer: authorizer

createRental:
  handler: methods/rentals.createRental
  events:
    - http:
        path: /rentals
        method: post
        cors: true
        authorizer: authorizer

acceptRental:
  handler: methods/rentals.acceptRental
  events:
    - http:
        path: /rentals/{rID}/accept
        method: post
        cors: true
        authorizer: authorizer

denyRental:
  handler: methods/rentals.denyRental
  events:
    - http:
        path: /rentals/{rID}
        method: delete
        cors: true
        authorizer: authorizer
