getRental:
  handler: methods/rentals.getRental
  events:
    - http:
        path: /rentals/{rID}
        method: get
        cors: true
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0
          type: request

listRentals:
  handler: methods/rentals.listRentals
  events:
    - http:
        path: /rentals
        method: get
        cors: true
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0
          type: request

createRental:
  handler: methods/rentals.createRental
  events:
    - http:
        path: /rentals
        method: post
        cors: true
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0
          type: request

acceptRental:
  handler: methods/rentals.acceptRental
  events:
    - http:
        path: /rentals/{rID}/accept
        method: post
        cors: true
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0
          type: request

denyRental:
  handler: methods/rentals.denyRental
  events:
    - http:
        path: /rentals/{rID}
        method: delete
        cors: true
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0
          type: request
