authorizer:
  handler: methods/authorizer.handler
getUserInfo:
  handler: methods/users.getUserInfo
  events:
    - http:
        path: /me
        cors: true
        method: get
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0
          type: request
getUserRentalRequests:
  handler: methods/users.getUserRentalRequests
  events:
    - http:
        path: /me/requests
        cors: true
        method: get
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0
          type: request
listUserProducts:
  handler: methods/users.listUserProducts
  events:
    - http:
        path: /me/products
        cors: true
        method: get
        authorizer:
          name: authorizer
          resultTtlInSeconds: 0
          type: request
clerkWebhook:
  handler: methods/clerk.clerkWebhook
  events:
    - http:
        path: /clerk
        method: post
