authorizer:
  handler: methods/authorizer.handler
  package:
    patterns:
      - methods/authorizer.js
      - node_modules/@clerk/**/*
      - node_modules/camelcase-keys/**/*
      - node_modules/cookie/**/*
      - node_modules/snakecase-keys/**/*
      - node_modules/tslib/**/*

getUserInfo:
  handler: methods/users.getUserInfo
  package:
    patterns:
      - methods/users.js
  events:
    - http:
        path: /me
        cors: true
        method: get
        authorizer: authorizer

#sendUserFeedback:
#  handler: methods/users.sendUserFeedback
#  package:
#    patterns:
#      - methods/users.js
#  events:
#    - http:
#        path: /user/{uID}/feedbacks
#        method: post
#        authorizer: authorizer
#
#getUserProducts:
#  handler: methods/users.getUserProducts
#  package:
#    patterns:
#      - methods/users.js
#  events:
#    - http:
#        path: /me/products
#        method: get
#        authorizer: authorizer
