authorizer:
  handler: methods/authorizer.handler
getUserInfo:
  handler: methods/users.getUserInfo
  events:
    - http:
        path: /me
        cors: true
        method: get
        authorizer: authorizer
clerkWebhook:
  handler: methods/users.clerkWebhook
  events:
    - http:
        path: /clerk
        method: post
#sendUserFeedback:
#  handler: methods/users.sendUserFeedback
#  package:
#    patterns:
#      - methods/users.js
#  events:
#    - http:
#        path: /user/{uID}/feedbacks
#        method: post
#        authorizer: authorizer
#
#getUserProducts:
#  handler: methods/users.getUserProducts
#  package:
#    patterns:
#      - methods/users.js
#  events:
#    - http:
#        path: /me/products
#        method: get
#        authorizer: authorizer
