authorizer:
  handler: methods/authorizer.handler
getUserInfo:
  handler: methods/users.getUserInfo
  events:
    - http:
        path: /me
        cors: true
        method: get
        authorizer: authorizer
getUserRentalRequests:
  handler: methods/users.getUserRentalRequests
  events:
    - http:
        path: /me/requests
        cors: true
        method: get
        authorizer: authorizer
listUserProducts:
  handler: methods/users.listUserProducts
  events:
    - http:
        path: /me/products
        cors: true
        method: get
        authorizer: authorizer
clerkWebhook:
  handler: methods/clerk.clerkWebhook
  events:
    - http:
        path: /clerk
        method: post
#sendUserFeedback:
#  handler: methods/users.sendUserFeedback
#  package:
#    patterns:
#      - methods/users.js
#  events:
#    - http:
#        path: /user/{uID}/feedbacks
#        method: post
#        authorizer: authorizer
#
